CREATE TABLE IF NOT EXISTS "public"."review" (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  count INTEGER,
  created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
