CREATE TABLE IF NOT EXISTS "public"."review" (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  course_id INTEGER NOT NULL UNIQUE,
  count INTEGER,
  created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("course_id") REFERENCES "public"."course"(id)
);
